/** 改变加载状态 */
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS;

/** 获取漫画首页信息 */
export const REQUEST_CARTOON_HOMEINFO = 'REQUEST_CARTOON_HOMEINFO';
export type REQUEST_CARTOON_HOMEINFO = typeof REQUEST_CARTOON_HOMEINFO;

/** 获取漫画详情信息 */
export const REQUEST_CARTOON_DETAILINFO = 'REQUEST_CARTOON_DETAILINFO';
export type REQUEST_CARTOON_DETAILINFO = typeof REQUEST_CARTOON_DETAILINFO;

/** 获取章节详情信息 */
export const REQUEST_CARTOON_SECTIONINFO = 'REQUEST_CARTOON_SECTIONINFO';
export type REQUEST_CARTOON_SECTIONINFO = typeof REQUEST_CARTOON_SECTIONINFO;

/** 查询动漫 */
export const REQUEST_SEARCH_CARTOON = 'REQUEST_SEARCH_CARTOON';
export type REQUEST_SEARCH_CARTOON = typeof REQUEST_SEARCH_CARTOON;

/** 根据动漫种类查询 */
export const REQUEST_CATEGORY_SEARCH = 'REQUEST_CATEGORY_SEARCH';
export type REQUEST_CATEGORY_SEARCH = typeof REQUEST_CATEGORY_SEARCH;
